blank_issues_enabled: false
contact_links:
  - name: Browse the current live job search
    url: https://workopia.io/browsejobs/au/casual?utm_source=github&utm_medium=repo&utm_campaign=uk-casual-part-time-jobs
    about: Search current UKn casual roles by title, location and date.
