import fs from 'node:fs';
export const escapeCell=value=>String(value??'—').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/[\r\n]+/g,' ');
const tiers=['Casual','Part-time','Contract-Temp'];
const tierOf=r=>r.tier==='Temp & Seasonal'?'Contract-Temp':r.employmentType;
const tierLabel=t=>t==='Contract-Temp'?'Temp & seasonal':t;
export function render(data){
 const rows=data.listings, when=new Date(data.meta.sourceTimestamp), date=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/London'}).format(when);
 const seasonal=rows.filter(r=>r.seasonal), christmas=rows.filter(r=>r.xmas === true), employers=new Set(rows.map(r=>r.company)).size;
 const age=r=>{const days=Math.floor((when-new Date(r.postedDateISO))/86400000);return days<=0?'today':days+'d';};
 const table=jobs=>'<table>\n<thead><tr>'+['Company','Role','Location','Pay','Shift','Checks','Apply','Age'].map(h=>'<th>'+h+'</th>').join('')+'</tr></thead>\n<tbody>\n'+jobs.map(r=>'<tr>'+[r.company,r.title+(!tiers.includes(r.employmentType)?' ['+r.employmentType+']':'')+(r.noExperience?' 🌱':'')+(r.xmas === true?' 🎄':''),r.location+(r.otherLocations?.length?' +'+r.otherLocations.length:''),r.salary||'—',r.weekend?'Weekend':'—',r.ticket||'—'].map(v=>'<td>'+escapeCell(v)+'</td>').join('')+'<td><a href="'+escapeCell(r.sourceUrl||'https://workopia.io/jobs/'+encodeURIComponent(r.id))+'">Apply →</a></td><td>'+age(r)+'</td></tr>').join('\n')+'\n</tbody>\n</table>';
 const lines=['# UK Casual, Part-Time & Temporary Jobs — Updated Daily','',...(data.meta.releaseReady?[]:['> Draft preview — not for publication.','']),`**${rows.length.toLocaleString('en-GB')} selected roles from ${employers.toLocaleString('en-GB')} employers**, from the employer-source snapshot dated **${date}**.`,'','## Explore beyond this selected directory','', '| GitHub directory | Live UK search |', '| --- | --- |', `| **${rows.length.toLocaleString('en-GB')} selected roles** | **${((data.meta.baseCasualCount||0)+(data.meta.expandedSearchCount||0)).toLocaleString('en-GB')} searchable postings** |`, '', `The search collection includes **${(data.meta.baseCasualCount||0).toLocaleString('en-GB')} casual, part-time and contract/temp postings**, plus **${(data.meta.expandedSearchCount||0).toLocaleString('en-GB')} related hourly/seasonal postings** with their real employment labels. Snapshot: **${data.meta.sourceTimestamp}**.`, '', 'This directory groups matching employer and role postings across locations and applies category and employer limits. Its selected-row count is not the full search collection or the entire UK job market.', '', '[**Search UK casual, part-time and temporary jobs on Workopia →**](https://workopia.io/casual-jobs/uk?utm_source=github&utm_medium=repo_readme). Apply through the employer links below or explore the wider search collection on Workopia.', '', 'Maintained by [Workopia](https://workopia.io). Counts refresh with the daily data pipeline.','', '## How to use this directory','','Choose your location and available shifts, check the advertised employment type, then confirm the details on the employer page before applying. This directory follows the same category and employment-tier structure as our [Australia directory](https://github.com/workopia/Australia-Casual-Part-Time-Jobs).','','### Live data summary','','| Measure | Repository snapshot |','| --- | ---: |',`| Selected roles | ${rows.length} |`,`| Employers | ${employers} |`,`| Seasonal roles in this directory (all seasons) | ${seasonal.length} |`,`| Christmas-tagged roles in this directory | ${christmas.length} |`,`| Explicitly no experience required | ${rows.filter(r=>r.noExperience).length} |`,`| Data date | ${date} |`,'','Counts describe this selected directory, not the entire UK market. Jobs are classified from Workopia’s employer-source feed and screened automatically; individual adverts are not all manually reverified each day.','','[Report incorrect data](../../issues/new/choose) · [Contribution guide](CONTRIBUTING.md)','','## Browse by category',''];
 for(const c of data.categories){const jobs=rows.filter(r=>r.category===c.key);if(jobs.length)lines.push(`- [${c.name}](#${c.key}) (${jobs.length}) — ${tiers.map(t=>tierLabel(t)+' '+jobs.filter(r=>tierOf(r)===t).length).join(' · ')}`);}
 if(christmas.length)lines.push('','## 🎄 Christmas-tagged roles','', 'The source feed tags these roles as Christmas casual. Check each employer advert for the actual season, contract and dates; summer and other seasonal tags are excluded.', '',table(christmas.slice(0,40)));
 if(seasonal.some(r=>!r.xmas))lines.push('','## Other seasonal roles','', 'Other seasonal work in this snapshot; a seasonal tag does not mean Christmas hiring. Check each advert for its dates.', '',table(seasonal.filter(r=>!r.xmas).slice(0,40)));
 for(const c of data.categories){const jobs=rows.filter(r=>r.category===c.key);if(!jobs.length)continue;lines.push('',`<a id="${c.key}"></a>`,`## ${c.name}`);for(const t of tiers){const selected=jobs.filter(r=>tierOf(r)===t);if(selected.length)lines.push('',`### ${tierLabel(t)} (${selected.length})`,'',table(selected));}}
 lines.push('','## Legend and scope','','- 🌱 The source explicitly says no experience is required.','- 🎄 The source feed specifically tags Christmas casual work; it is not independent confirmation that Christmas recruitment is open.','- Pay, shifts and checks are shown only where available; — means not specified.','- Casual, part-time and temporary are separate employment labels. This directory does not apply Australian casual-loading rules to UK contracts.','- Related full-time/hourly roles may appear in website search with their actual type; they do not inflate the base casual count. Explicitly seasonal roles can enter the seasonal tier while retaining their actual employment label.','','## Updates and history','','The daily publisher validates the dataset, renders this README and updates [data/active.json](data/active.json) from the same snapshot. Empty, stale or sharply reduced releases are rejected, keeping the previous published version. Removed rows are recorded as no longer selected, not automatically declared closed.','','Structured data: [.github/scripts/listings.json](.github/scripts/listings.json). UK uses GB for country data, uk for website URLs, GBP for currency and Europe/London for dates.');
 return lines.join('\n')+'\n';
}
if(process.argv[1]&&import.meta.url===new URL('file://'+process.argv[1]).href){const d=JSON.parse(fs.readFileSync('.github/scripts/listings.json','utf8')),md=render(d);if(process.argv.includes('--check')){if(fs.readFileSync('README.md','utf8')!==md)throw new Error('README does not match listings');}else fs.writeFileSync('README.md',md);}

export function renderPreview(md) {
 const safe=md.replace(/<\/script>/g,'<\\/script>');
 return `<!doctype html><meta charset=utf-8><meta name="robots" content="noindex"><link rel=stylesheet href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown.min.css"><script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script><style>body{max-width:1012px;margin:auto;padding:32px}table{width:100%}</style><article class=markdown-body id=o></article><script id=md type=text/plain>${safe}</script><script>o.innerHTML=marked.parse(md.textContent)</script>`;
}
