import fs from 'node:fs';
export const escapeCell=value=>String(value??'—').replace(/\|/g,'\\|').replace(/[<>]/g,'').replace(/[\r\n]+/g,' ');
export function render(data){
 const rows=data.listings, date=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/London'}).format(new Date(data.meta.sourceTimestamp));
 const lines=[`# UK Part-Time, Temporary & Casual Jobs`, '', ...(data.meta.releaseReady ? [] : ['> Draft preview — source verification is incomplete. Not for publication.', '']), `Updated from the source snapshot dated **${date}**.`, '', `${rows.length.toLocaleString('en-GB')} selected UK listings across ${new Set(rows.map(r=>r.company)).size.toLocaleString('en-GB')} employer labels. This is a selected directory, not a count of the whole UK jobs market.`, '', `[Explore UK jobs on Workopia](https://workopia.io/casual-jobs/uk?utm_source=github&utm_medium=repository) · [Report a problem](../../issues/new/choose)`, '', '## Browse jobs',''];
 for(const cat of data.categories){const jobs=rows.filter(r=>r.category===cat.key);if(!jobs.length)continue;lines.push(`### ${cat.name}`,'','| Employer | Role | Location | Type | Advertised pay | Job |','| --- | --- | --- | --- | --- | --- |');for(const r of jobs)lines.push(`| ${escapeCell(r.company)} | ${escapeCell(r.title)} | ${escapeCell(r.location)} | ${escapeCell(r.employmentType)} | ${escapeCell(r.salary)} | [View job](https://workopia.io/jobs/${encodeURIComponent(r.id)}) |`);lines.push('');}
 lines.push('## About this directory','','Listings are selected from Workopia’s UK job dataset. Availability and advertised conditions can change; check the employer posting before applying. Unknown pay is shown as —. Jobs leaving this selected directory are not automatically classified as closed.','','The structured data is in [.github/scripts/listings.json](.github/scripts/listings.json). Changes to the data regenerate this README.');
 return lines.join('\n')+'\n';
}
if(process.argv[1] && import.meta.url===new URL('file://'+process.argv[1]).href){const data=JSON.parse(fs.readFileSync('.github/scripts/listings.json','utf8'));const md=render(data);if(process.argv.includes('--check')){if(fs.readFileSync('README.md','utf8')!==md)throw new Error('README does not match listings');}else fs.writeFileSync('README.md',md);}
